### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by 0903W** [Rabbitminers/Extended-Bogeys#24]
hello author
The problem I encountered is that after installing this mod, it will crash and flash back when I go to bed
Game version: 1.18.2

Crash report:
https://drive.google.com/file/d/1EDKLOa-lh3AF2JAYwcWwdmaXtKDmU_Lp/view?usp=sharing

**Comment by Rabbitminers** [comment]
I havent been able to reproduce this, can you try it again without rpmtw and send me the new log, Thanks.

**Comment by Rabbitminers** [comment]
Should be fixed now our API sits in create and we dont use as many mixins
