### ISSUE TITLE
Bogeys disappear using Optifine or Rubidium & Oculus

### ISSUE THREAD

**Issue by Lucreeper74** [Rabbitminers/Extended-Bogeys#27]
**Describe the bug**
When activate shader, if train is assembled (no solid blocks), the bogeys disappear. When i disable shader or disassemble the train, they came back.

**To Reproduce**
Use Rubidium 0.5.4
Oculus 1.4.3a
Extended Boggeys 0.3.8-1.18.2-0.5.0h

https://user-images.githubusercontent.com/85123779/221438421-fe7429e6-2adf-439f-bbf2-473ce03ae590.mp4

**Comment by Rabbitminers** [comment]
https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat
