### ISSUE TITLE
These bogeys is not good for a 45decree curve

### ISSUE THREAD

**Issue by Lucreeper74** [Rabbitminers/Extended-Bogeys#28]
**Describe the bug**
These bogeys not centered on the rails.

**To Reproduce**
Use Rubidium 0.5.4
Oculus 1.4.3a
Extended Boggeys 0.3.8-1.18.2-0.5.0h

Found by KenWithHat#9172 for additionnal information.

![image](https://user-images.githubusercontent.com/85123779/221438850-1fe2bc9f-683b-43b5-a47f-490fac9297e5.png)

**Comment by Rabbitminers** [comment]
An opt-in de-railment config will be added to prevent this from occurring
