### ISSUE TITLE
error during loading mods

### ISSUE THREAD

**Issue by dykuyui** [Rabbitminers/Extended-Bogeys#31]
**Describe the bug**
error loading mods

**To Reproduce**
1. Extended Bogeys Version 1.0.0-1.19.2-0.5.0.i
2. Minecraft Version 1.19.2 forge
3. Create Version 0.5.0.i
4. Other modlist : (1. alloyed v1.5 (2. controllable 0.17.0  (3. createdeco 1.2.12 (3. dbextended 5.1 (4. flywheel foge (5. framed blocks 6.7.0 (6. stem n rails 1.1.1 (7. tl_skim_cape_forge1.28 (8. worldedit-mod 7.2.12

**Expected behavior**
it should loadup with out any problems because every thing is working fine before i install this

**Screenshots**
If applicable, add screenshots to help ex
![Screenshot (81)](https://user-images.githubusercontent.com/121882388/236420472-d0bcf0c4-d3e9-4c77-88be-f8aa9561fd28.png)
plain your problem.

**Additional context**

**Comment by SpottyTheTurtle** [comment]
Please do not open issues without proving any information whatsoever as to the problem you're experiencing. The template is for you to fill out, it's not meant to be completely ignored and sent in unchanged.

**Comment by dykuyui** [comment]
> Please do not open issues without proving any information whatsoever as to the problem you're experiencing. The template is for you to fill out, it's not meant to be completely ignored and sent in unchanged.

**Comment by dykuyui** [comment]
sorry iam doing it for first time

**Comment by Rabbitminers** [comment]
This is an april fools release of the mod, you can download official betas from our discord
