### ISSUE TITLE
No Curseforge page. Link Gives 404 error.

### ISSUE THREAD

**Issue by Nyquil98** [Rabbitminers/Extended-Bogeys#32]
Title.
Curseforge link doesn't work, cant find your mod when searching for it on curseforge either. Is this intended?

**Screenshots**
![image](https://github.com/Rabbitminers/Extended-Bogeys/assets/133042360/67b00a24-82cb-4f23-99b9-d5b8ac44bfb9)
![image](https://github.com/Rabbitminers/Extended-Bogeys/assets/133042360/8a6f8656-682c-4c8e-8628-07fc84303e3f)

**Comment by SpottyTheTurtle** [comment]
It's not out on curseforge yet, join the discord if you want to download the beta.

**Comment by Rabbitminers** [comment]
The curseforge page link is just used as a place holder until we are ready for release
