### ISSUE TITLE
Train casings not working

### ISSUE THREAD

**Issue by Cadmium620** [Rabbitminers/Extended-Bogeys#33]
**Describe the bug**

**To Reproduce**
1. Extended Bogeys Version 0.38
2. Minecraft Version 1.18.2
3. Create Version 0.5i
4. Other modlist --> https://hastebin.com/share/uhaluyapef.vbnet

**Expected behavior**
If you place the train casing and change the bogey everything as it should be. if you build the train the bogey converts to a 
normal create bogey

**Screenshots**

![2023-05-20_00 34 45](https://github.com/Rabbitminers/Extended-Bogeys/assets/106585614/6a172817-3fe4-49a9-8b7b-96b391d48333)

**Additional context**
THE SHADER IS NOT THE PROBLEM.

**Comment by Rabbitminers** [comment]
Extended Bogeys Depends on instanced rendering to render each bogey uniquely. 

Run `/flywheel backend instanced` to fix this
