### ISSUE TITLE
Crashing Whenever bogey is placed on track 1.19.2 0.5.1.b 0.4.1 Ex.B.

### ISSUE THREAD

**Issue by verddecent** [Rabbitminers/Extended-Bogeys#36]
**Describe the bug**
No other crashes except for whenever placing a bogey it crashes the game

**To Reproduce**
1. 0.4.3 - 1.19.2 - 0.5.1.b
2. 1.19.2 Forge
3. 0.5.1.b
4. Launch World
5. Setup Train Station
6. Start Train Build
7. Place Bogey On Track
8. Crash

**Expected behavior**
I Expected it to work and to actually place the bogey without crashing.

**Screenshots**
Dont know how to add screenshots.
 

**Additional context**
https://bytebin.lucko.me/in4Xwr0vxZ - Crash Report

Crash screen (Not Enough Crashes Mod)
Says Create,Extended Bogeys,Rubidium on the suspected mods for the crash on the screen i just dont know how to add screenshots.

**Comment by Rabbitminers** [comment]
Hey, can you re-upload that crash report, the link seems to have expired. Also perhaps try disabling shaders if  you are using them see if that changes anything.

**Comment by verddecent** [comment]
i dont use shaders as im on a home mac and shaders basically make it unplayable. i will try to find out how to send a pic or smthin

**Comment by verddecent** [comment]
![Screenshot 2023-07-11 at 4 28 07 PM](https://github.com/Rabbitminers/Extended-Bogeys/assets/128002522/0b58c2f8-8e77-441f-9232-321c2a45caaf)

**Comment by verddecent** [comment]
not enough crashes thingy

**Comment by verddecent** [comment]
[crash-2023-07-11_16.27.50-client.txt](https://github.com/Rabbitminers/Extended-Bogeys/files/12116874/crash-2023-07-11_16.27.50-client.txt)
found the crashreport too

**Comment by IdkWhosThis** [comment]
I'm running into the same issue on forge
My logs: https://mclo.gs/LANaTAn

**Comment by Rabbitminers** [comment]
Looks like you're both using create 0.5.1.c, Extended bogeys isn't compatible with the changes I made in that version yet. In the mean time if you're able to try using 0.5.1.b
