### ISSUE TITLE
Fake

### ISSUE THREAD

**Issue by traincrisis** [Rabbitminers/Extended-Bogeys#37]
The mod does not exists on CurseForge, could you re-release it?

**Comment by Rabbitminers** [comment]
Extended Bogeys  is currently in public beta, (It hasnt been released at all yet), you can find compiled versions of the mod on our discord server to test. We do this so we can better convey that the mod is in beta and so people can directly report back bugs they find without needing to seek us out like they would on platforms such as curse forge. We aren't far off our first full release at which point you'll be able to download the mod on curse forge as well as modrinth
