### ISSUE TITLE
1.18.2 forge crashing when placing ANY bogey

### ISSUE THREAD

**Issue by Cha0sraf34** [Rabbitminers/Extended-Bogeys#43]
**Describe the bug**
whenever i try to create a new train (placing a bogey) it crashes the game, that's it.

**To Reproduce**
1. Extended Bogeys 0.4.3
2. Minecraft 1.18.2 (forge newest i guess)
3. Create 0.5.1.f
4. Other modlist
- create big cannons
- create deco
- just enough items

**Expected behavior**
expected the game not to crash.

**Additional context**
here is the log from when it crashed

[latest.log](https://github.com/Rabbitminers/Extended-Bogeys/files/13798140/latest.log)

**Comment by Szedann** [comment]
Extended bogeys isn't compatible with create 0.5.1.f, you have to use 0.5.1.b

**Comment by Cha0sraf34** [comment]
thanks, i'll see if that fixes it, probably will though

**Comment by Rabbitminers** [comment]
> thanks, i'll see if that fixes it, probably will though

Is everything working?
